### ISSUE TITLE
How we can combine multiple transaction in single transaction?

### ISSUE THREAD

**Issue by dsk7990** [mofalabs/sui#1]
I want to merge / combine multiple transaction like split coin, move coin in single transaction. So how can i do using this sdk?

**Comment by 0xmove** [comment]
@dsk7990 Not supported yet. Maybe it will be supported in the next version.

**Comment by dsk7990** [comment]
@0xmove okay, when can i expect this one in future release?

**Comment by 0xmove** [comment]
@dsk7990 You can submit a PR.

**Comment by dsk7990** [comment]
@0xmove not able to solve it, can you please share reference if you have any.

**Comment by 0xmove** [comment]
PTB has merged into main branch, please refer to test case for usage.

**Comment by dsk7990** [comment]
Thank you for support
