### ISSUE TITLE
Want to submit a PR for JsonRpcClient

### ISSUE THREAD

**Issue by yiichenhi** [mofalabs/sui#4]
Hi! thanks for your package.

small fix for adding headers to JsonRpcClient

I need the collaborator access.

**Comment by 0xmove** [comment]
Hi Yii. Thanks for your help.

You can just submit a PR. Did you encounter any problems during the
submission process?

**Comment by chyiiiiiiiiiiii** [comment]
Now it's fixed. Just need the collaborator's permission.
