### ISSUE TITLE
Request the signAndExecuteTransactionBlock Function for zklogin

### ISSUE THREAD

**Issue by hien-p** [mofalabs/sui#6]
Hi, 
We have seen the 'test' folder in zklogin. It appears that the ZkLoginSignature used in this test is 'zkLoginSignature'."

<img width="489" alt="image" src="https://github.com/mofalabs/sui/assets/70145901/7d711c89-bafd-44f3-927e-44a3d17a49ac">

In [zklogin demo](https://sui-zklogin.vercel.app/#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImFkZjVlNzEwZWRmZWJlY2JlZmE5YTYxNDk1NjU0ZDAzYzBiOGVkZjgiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI1NzMxMjAwNzA4NzEtMGs3Z2E2bnM3OWllMGpwZzFlaTZpcDV2amUyb3N0dDYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1NzMxMjAwNzA4NzEtMGs3Z2E2bnM3OWllMGpwZzFlaTZpcDV2amUyb3N0dDYuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDYxMzE5NzE3MTQ2MjA3MDU5MjkiLCJub25jZSI6IlM4UVF3TXg0UGltcUU0X2NtWHVfMWZKN0pEUSIsIm5iZiI6MTcxMTcwNDI0NywiaWF0IjoxNzExNzA0NTQ3LCJleHAiOjE3MTE3MDgxNDcsImp0aSI6ImUzMzZiODc0ZDI5MWMyM2UyMDE2NzQzZDgzNjI0MzdjNGMyYTQ5MTMifQ.YgbWxr1ljY6mFZzfml3Y8USX_G097Fydnj9Gd9Um0LzzfYTXG0ANZF3zWLres4ss3-15rthDasGTk-ChLh0-T0H4ryVnKYPF_Sw75NhBAdsNgIHeGRoYm-rqIaYplO9Te33a6ZD9FQK8QY0LsbAqAoeNxasGowSm1NRQvjAO9B-t35yiaz-LQmYTme4TNqpoJ5TANfs8hzENFeHDef9JtUJJgsolLGgbv855IbvPk_McsfjbCeUX4nOImQWXjzQLdSZVj5g5kFIPNF8xn4Se7qV6NiclAGJy7bexOd1wQQI7TKffjoqnjPSUrb1TlLwqF7-Ih7EKLW9NSX98x8haLg&authuser=0&prompt=none:~:text=//%20Execute%20transaction%0AsuiClient.executeTransactionBlock(%7B%0A%20%20transactionBlock%3A%20bytes%2C%0A%20%20signature%3A%20zkLoginSignature%2C%0A%7D)%3B), we see the function here:

<img width="807" alt="image" src="https://github.com/mofalabs/sui/assets/70145901/28189038-34e7-4093-88b2-c0eae0a810ae">

How can we implement the 'executeTransactionBlock' function using your libraries? 

Looking forward to your response with examples.

**Comment by 0xmove** [comment]
You can also use the `executeTransactionBlock` method of `SuiClient`.

Here is a zkLogin [example](https://github.com/mofalabs/zklogin/blob/main/test/zklogin_test.dart)
